/*==============================================================================
TEARDOWN ALL - Backstage Label Analytics
Pair-programmed by SE Community + Cortex Code | Expires: 2026-10-22

Removes everything this demo created, and nothing else.

USAGE
  Snowsight: open a new worksheet, paste this file, click Run All.
  Terminal:  snow sql -c <connection> -f teardown_all.sql

DELIBERATELY NOT DROPPED -- these are shared across SE demo projects:
  SNOWFLAKE_EXAMPLE                     database
  SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS     schema (only this project's views inside it)

Every drop below names one object. There is no DROP DATABASE and no CASCADE. The
project schema is dropped with RESTRICT so that an unexpected dependency raises an
error instead of silently taking something else with it.
==============================================================================*/

USE ROLE SYSADMIN;

-- 1. Agent first: it references the semantic views.
DROP AGENT IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.BACKSTAGE_ANALYTICS_AGENT;

-- 2. Semantic views, which live in the shared SEMANTIC_MODELS schema.
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_BACKSTAGE_REVENUE;
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_BACKSTAGE_DAILY_STREAMS;

-- 3. Detach row access policies before dropping them. A policy attached to a
--    table cannot be dropped, and DROP ALL ROW ACCESS POLICIES succeeds even when
--    nothing is attached, so this is safe on a partially deployed schema.
ALTER TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.FACT_ROYALTY_MONTH DROP ALL ROW ACCESS POLICIES;
ALTER TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.FACT_STREAM_DAY    DROP ALL ROW ACCESS POLICIES;
ALTER TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_LABEL          DROP ALL ROW ACCESS POLICIES;
ALTER TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_TRACK          DROP ALL ROW ACCESS POLICIES;

DROP ROW ACCESS POLICY IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.LABEL_REVENUE_POLICY;
DROP ROW ACCESS POLICY IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.LABEL_STREAMS_POLICY;
DROP ROW ACCESS POLICY IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.LABEL_LOOKUP_POLICY;

-- 4. Analytic views.
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_TRACK_TITLE_AMBIGUITY;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_STREAM_COVERAGE;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_DAILY_STREAMS;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_LABEL_REVENUE;

-- 5. Facts, dimensions, and configuration.
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.FACT_STREAM_DAY;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.FACT_ROYALTY_MONTH;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.ENTITLEMENT;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_ACTIVITY_DAY;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_STATEMENT_MONTH;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_TRACK;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_DSP_SERVICE;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_LABEL;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DEMO_CONFIG;

-- 6. Project schema. RESTRICT, never CASCADE.
DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS RESTRICT;

-- 7. Warehouse.
DROP WAREHOUSE IF EXISTS SFE_BACKSTAGE_ANALYTICS_WH;

-- 8. Persona roles.
USE ROLE USERADMIN;
DROP ROLE IF EXISTS BACKSTAGE_LABEL_BROAD;
DROP ROLE IF EXISTS BACKSTAGE_LABEL_LIMITED;
DROP ROLE IF EXISTS BACKSTAGE_LABEL_NONE;

USE ROLE SYSADMIN;

SELECT 'Backstage Label Analytics removed.' AS status,
       'SNOWFLAKE_EXAMPLE and SEMANTIC_MODELS were preserved.' AS note;
