/*==============================================================================
06_grants.sql - Backstage Label Analytics
Pair-programmed by SE Community + Cortex Code | Expires: 2026-10-22

Persona grants. Run last, after the semantic views and the agent exist.

Two things that are easy to get wrong:

1. A role needs both SELECT and REFERENCES on a semantic view it does not own in
   order to use it through a Cortex Agent. SELECT alone is enough to query the
   view directly, so this failure looks like an agent problem rather than a grant
   problem and the error message does not mention the missing privilege.

2. ENTITLEMENT is never granted to a persona. The row access policies read it
   under the policy owner's rights, so scoping works without the persona being
   able to see or modify its own authorization.
==============================================================================*/

USE ROLE SECURITYADMIN;

/*------------------------------------------------------------------------------
Shared grants for all three personas. BACKSTAGE_LABEL_NONE receives the same
object privileges as the others on purpose: its emptiness must come from the
entitlement model, not from a missing grant. A persona that fails with
"insufficient privileges" has proven nothing about row-level scoping.
------------------------------------------------------------------------------*/

-- Object access
GRANT USAGE ON WAREHOUSE SFE_BACKSTAGE_ANALYTICS_WH TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT USAGE ON WAREHOUSE SFE_BACKSTAGE_ANALYTICS_WH TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT USAGE ON WAREHOUSE SFE_BACKSTAGE_ANALYTICS_WH TO ROLE BACKSTAGE_LABEL_NONE;

GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE BACKSTAGE_LABEL_NONE;

GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS TO ROLE BACKSTAGE_LABEL_NONE;

GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS TO ROLE BACKSTAGE_LABEL_NONE;

-- Facts, dimensions, and analytic views. Row access policies do the scoping.
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.FACT_ROYALTY_MONTH  TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.FACT_ROYALTY_MONTH  TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.FACT_ROYALTY_MONTH  TO ROLE BACKSTAGE_LABEL_NONE;

GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.FACT_STREAM_DAY     TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.FACT_STREAM_DAY     TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.FACT_STREAM_DAY     TO ROLE BACKSTAGE_LABEL_NONE;

GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_LABEL           TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_LABEL           TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_LABEL           TO ROLE BACKSTAGE_LABEL_NONE;

GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_TRACK           TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_TRACK           TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_TRACK           TO ROLE BACKSTAGE_LABEL_NONE;

GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_DSP_SERVICE     TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_DSP_SERVICE     TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_DSP_SERVICE     TO ROLE BACKSTAGE_LABEL_NONE;

GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_STATEMENT_MONTH TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_STATEMENT_MONTH TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_STATEMENT_MONTH TO ROLE BACKSTAGE_LABEL_NONE;

GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_ACTIVITY_DAY    TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_ACTIVITY_DAY    TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.DIM_ACTIVITY_DAY    TO ROLE BACKSTAGE_LABEL_NONE;

GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_LABEL_REVENUE         TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_LABEL_REVENUE         TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_LABEL_REVENUE         TO ROLE BACKSTAGE_LABEL_NONE;

GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_DAILY_STREAMS         TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_DAILY_STREAMS         TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_DAILY_STREAMS         TO ROLE BACKSTAGE_LABEL_NONE;

GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_STREAM_COVERAGE       TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_STREAM_COVERAGE       TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_STREAM_COVERAGE       TO ROLE BACKSTAGE_LABEL_NONE;

GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_TRACK_TITLE_AMBIGUITY TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_TRACK_TITLE_AMBIGUITY TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT ON VIEW SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.V_TRACK_TITLE_AMBIGUITY TO ROLE BACKSTAGE_LABEL_NONE;

-- Semantic views: SELECT and REFERENCES are both required for agent use.
GRANT SELECT, REFERENCES ON SEMANTIC VIEW SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_BACKSTAGE_REVENUE       TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT, REFERENCES ON SEMANTIC VIEW SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_BACKSTAGE_REVENUE       TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT, REFERENCES ON SEMANTIC VIEW SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_BACKSTAGE_REVENUE       TO ROLE BACKSTAGE_LABEL_NONE;

GRANT SELECT, REFERENCES ON SEMANTIC VIEW SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_BACKSTAGE_DAILY_STREAMS TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT SELECT, REFERENCES ON SEMANTIC VIEW SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_BACKSTAGE_DAILY_STREAMS TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT SELECT, REFERENCES ON SEMANTIC VIEW SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_BACKSTAGE_DAILY_STREAMS TO ROLE BACKSTAGE_LABEL_NONE;

-- Agent access
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE BACKSTAGE_LABEL_NONE;

GRANT USAGE ON AGENT SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.BACKSTAGE_ANALYTICS_AGENT TO ROLE BACKSTAGE_LABEL_BROAD;
GRANT USAGE ON AGENT SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.BACKSTAGE_ANALYTICS_AGENT TO ROLE BACKSTAGE_LABEL_LIMITED;
GRANT USAGE ON AGENT SNOWFLAKE_EXAMPLE.BACKSTAGE_ANALYTICS.BACKSTAGE_ANALYTICS_AGENT TO ROLE BACKSTAGE_LABEL_NONE;

/*
 Deliberately NOT granted to any persona:
   ENTITLEMENT  - a persona must not read or alter its own authorization
   DEMO_CONFIG  - generation internals
*/

-- Restore SYSADMIN. Anything that reads the policy-protected tables after this
-- script needs a role that holds entitlements, and SECURITYADMIN does not. Leaving
-- the session as SECURITYADMIN makes every fact table look empty.
USE ROLE SYSADMIN;
